# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.arange(5,30,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [7]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [10]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(2,4)

array([[0.31074786, 0.4147664 , 0.56169531, 0.54901056],
       [0.26770704, 0.89978193, 0.05851128, 0.21902787]])

In [13]:
np.random.rand(2,7)

array([[0.71340088, 0.66410163, 0.44543873, 0.31439698, 0.10261472,
        0.93467298, 0.97116054],
       [0.79920673, 0.00338602, 0.59791934, 0.78089004, 0.38217189,
        0.30836759, 0.06617302]])

In [14]:
np.random.randint(2,10)

7

In [15]:
np.random.randint(20,56,100)

array([25, 42, 34, 34, 28, 22, 23, 33, 29, 47, 54, 50, 23, 53, 20, 38, 30,
       20, 47, 43, 33, 23, 31, 44, 50, 22, 25, 45, 55, 31, 35, 42, 48, 35,
       38, 54, 49, 32, 46, 27, 42, 50, 22, 38, 22, 42, 52, 39, 44, 22, 42,
       41, 25, 51, 44, 25, 23, 33, 26, 51, 52, 45, 28, 42, 47, 26, 42, 44,
       25, 37, 45, 50, 44, 49, 21, 24, 55, 54, 41, 53, 35, 43, 23, 31, 24,
       47, 20, 49, 28, 43, 34, 50, 22, 49, 37, 20, 39, 32, 42, 27])

In [16]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
rand_array=np.random.randint(0,100,20)
rand_array

array([75, 82, 70, 67, 91, 51, 99, 54, 87, 25, 98, 51,  8, 30, 47,  8, 95,
       38, 29, 58])

In [18]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [19]:
rand_array.max()

99

In [20]:
rand_array.argmax()

6

In [21]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
sample_array.shape

(30,)

In [23]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
sample_array.dtype

dtype('int32')

In [25]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a=np.random.rand(2,3)
a

array([[0.01464203, 0.51010235, 0.15576052],
       [0.23698856, 0.6307261 , 0.31108839]])

In [28]:
a.T

array([[0.01464203, 0.23698856],
       [0.51010235, 0.6307261 ],
       [0.15576052, 0.31108839]])

In [29]:
import numpy as np

In [30]:
sample_array=np.arange(10,21)


In [31]:
sample_array[8]

18

In [32]:
sample_array[2:5]

array([12, 13, 14])

In [33]:
sample_array[[2,5]]

array([12, 15])

In [34]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [35]:
sample_array=np.arange(10,21)
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [36]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [37]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two-Dimensional array

In [38]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [39]:
sample_matrix[0][2]

1

In [40]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [41]:
sample_matrix[2]

array([56, 76, 24,  7])

### Custom indexing

In [42]:
sample_matrix=np.array(([30,10,1,23],[24,21,32,33],[6,76,24,7]))
sample_matrix

array([[30, 10,  1, 23],
       [24, 21, 32, 33],
       [ 6, 76, 24,  7]])

In [43]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 32],
       [ 7, 24]])

###  Selection techniques

In [44]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [45]:
bool=sample_array<10
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [46]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [48]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [49]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [50]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [51]:
np.max(sample_array)

30

In [52]:
np.min(sample_array)

1

In [53]:
np.argmax(sample_array)

29

In [54]:
np.argmin(sample_array)

0

In [55]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [56]:
np.std(sample_array)

8.65544144839919

In [57]:
np.var(sample_array)


74.91666666666667

In [58]:
np.mean(sample_array)

15.5

In [59]:
array=np.random.randn(3,6)
array

array([[ 1.39458739, -0.84328211,  2.26189353,  0.21506162, -0.24064902,
        -0.99734686],
       [ 0.53607029, -0.49194679, -0.79867858, -0.18810396, -1.43742108,
        -0.69908437],
       [-0.73295749, -0.18565005,  0.15100154,  0.48375628,  0.1388332 ,
         2.10810118]])

In [60]:
np.round(array,decimals=2)

array([[ 1.39, -0.84,  2.26,  0.22, -0.24, -1.  ],
       [ 0.54, -0.49, -0.8 , -0.19, -1.44, -0.7 ],
       [-0.73, -0.19,  0.15,  0.48,  0.14,  2.11]])

In [61]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

# Pandas

In [62]:
import pandas as pd

In [63]:
labels=['w','x','y','z']
list=[10,20,30,40]
array=np.array([10,20,30,40])
dict={'w':10,'x':20,'y':30,'z':40}


In [64]:
pd.Series(data=list)

0    10
1    20
2    30
3    40
dtype: int64

In [65]:
pd.Series(data=list,index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [66]:
pd.Series(array,labels)

w    10
x    20
y    30
z    40
dtype: int32

In [67]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

### Pandas dataframe and indexing

In [68]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [69]:
sports1['cricket']

1

In [70]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [71]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [73]:
df1=pd.DataFrame(np.random.randn(8,5),index='A B C D E F G H '.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

df1['Score3']



A    1.718498
B    0.764495
C    0.579830
D    0.216452
E    0.591557
F    0.017519
G   -0.882286
H   -0.786689
Name: Score3, dtype: float64

In [74]:
df1[['Score2','Score1']]

df1['Score6']=df1['Score1']+df1['Score2']
df1



Score1    Score2    Score3    Score4    Score5    Score6
A  0.004812 -0.973157  1.718498 -1.006480 -0.555031 -0.968346
B  0.886039  0.677599  0.764495 -1.368421 -0.116150  1.563639
C  0.265524 -0.671344  0.579830 -0.231044 -1.768153 -0.405820
D  0.955658  1.273142  0.216452  0.450457  0.005644  2.228800
E -0.266536  0.566529  0.591557  1.029330  0.709537  0.299992
F -0.452065 -0.800828  0.017519 -0.145961 -2.442345 -1.252893
G  0.906852 -0.412967 -0.882286  0.058606  2.452959  0.493885
H  0.252164 -0.066716 -0.786689 -0.547181  1.166676  0.185448

In [75]:
df1.drop('Score5',axis=1)



Score1    Score2    Score3    Score4    Score6
A  0.004812 -0.973157  1.718498 -1.006480 -0.968346
B  0.886039  0.677599  0.764495 -1.368421  1.563639
C  0.265524 -0.671344  0.579830 -0.231044 -0.405820
D  0.955658  1.273142  0.216452  0.450457  2.228800
E -0.266536  0.566529  0.591557  1.029330  0.299992
F -0.452065 -0.800828  0.017519 -0.145961 -1.252893
G  0.906852 -0.412967 -0.882286  0.058606  0.493885
H  0.252164 -0.066716 -0.786689 -0.547181  0.185448

In [ ]:
df1.reset_index()



In [76]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123